In [1]:
import numpy as np

# Array 1D (une dimension) — comme une liste
arr1 = np.array([1, 2, 3, 4, 5])
print("Array 1D :", arr1)
print("Type :", type(arr1))
print("Dtype :", arr1.dtype)  # type des éléments
print("Shape :", arr1.shape)  # dimensions

Array 1D : [1 2 3 4 5]
Type : <class 'numpy.ndarray'>
Dtype : int64
Shape : (5,)


In [2]:
# Array 2D (deux dimensions) — comme un tableau Excel
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("Array 2D :\n", arr2)
print("Shape :", arr2.shape)   # (3 lignes, 3 colonnes)
print("Dimensions :", arr2.ndim)  # nombre de dimensions
print("Taille totale :", arr2.size)  # nombre total d'éléments

Array 2D :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape : (3, 3)
Dimensions : 2
Taille totale : 9


In [3]:
# Pas besoin de taper les valeurs à la main !

# Array de zéros
zeros = np.zeros((3, 4))
print("Zeros :\n", zeros)

# Array de uns
uns = np.ones((2, 3))
print("\nUns :\n", uns)

# Matrice identité (tu connais ça en algèbre linéaire !)
identite = np.eye(4)
print("\nMatrice identité :\n", identite)

# Array avec des valeurs régulièrement espacées
lineaire = np.linspace(0, 10, 5)  # 5 valeurs entre 0 et 10
print("\nLinspace :", lineaire)

# Array avec un pas défini
pas = np.arange(0, 20, 3)  # de 0 à 20 avec un pas de 3
print("Arange :", pas)

Zeros :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Uns :
 [[1. 1. 1.]
 [1. 1. 1.]]

Matrice identité :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Linspace : [ 0.   2.5  5.   7.5 10. ]
Arange : [ 0  3  6  9 12 15 18]


In [4]:
# Fixer le seed pour avoir les mêmes résultats à chaque exécution
np.random.seed(42)

# Nombres aléatoires entre 0 et 1
aleatoire = np.random.rand(3, 3)
print("Aléatoire entre 0 et 1 :\n", aleatoire)

# Nombres aléatoires entiers
entiers = np.random.randint(0, 100, size=(3, 4))
print("\nEntiers aléatoires :\n", entiers)

# Distribution normale (moyenne=0, écart-type=1)
normale = np.random.randn(4, 4)
print("\nDistribution normale :\n", normale)

Aléatoire entre 0 et 1 :
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Entiers aléatoires :
 [[23  2 21 52]
 [ 1 87 29 37]
 [ 1 63 59 20]]

Distribution normale :
 [[ 1.46237812  1.53871497 -2.43910582  0.60344123]
 [-0.25104397 -0.16386712 -1.47632969  1.48698096]
 [-0.02445518  0.35555132  0.41701111  0.83246186]
 [-0.29339915 -0.02983857  0.09512578  0.66465434]]


In [5]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Accéder à un élément (commence à 0)
print("Premier élément :", arr[0])
print("Dernier élément :", arr[-1])
print("Troisième élément :", arr[2])

# Slicing (comme Python mais plus puissant)
print("\nDu début au 4ème :", arr[:4])
print("Du 3ème à la fin :", arr[3:])
print("Du 2ème au 6ème :", arr[2:6])
print("Un élément sur deux :", arr[::2])
print("Tableau inversé :", arr[::-1])

Premier élément : 10
Dernier élément : 90
Troisième élément : 30

Du début au 4ème : [10 20 30 40]
Du 3ème à la fin : [40 50 60 70 80 90]
Du 2ème au 6ème : [30 40 50 60]
Un élément sur deux : [10 30 50 70 90]
Tableau inversé : [90 80 70 60 50 40 30 20 10]


In [6]:
matrice = np.array([[1,  2,  3,  4],
                    [5,  6,  7,  8],
                    [9, 10, 11, 12]])

print("Matrice complète :\n", matrice)

# Accéder à un élément [ligne, colonne]
print("\nÉlément ligne 0, colonne 2 :", matrice[0, 2])
print("Élément ligne 2, colonne 3 :", matrice[2, 3])

# Extraire une ligne entière
print("\nPremière ligne :", matrice[0, :])
print("Dernière ligne :", matrice[-1, :])

# Extraire une colonne entière
print("\nPremière colonne :", matrice[:, 0])
print("Deuxième colonne :", matrice[:, 1])

# Extraire une sous-matrice
print("\nSous-matrice (2x2) :\n", matrice[0:2, 0:2])

Matrice complète :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Élément ligne 0, colonne 2 : 3
Élément ligne 2, colonne 3 : 12

Première ligne : [1 2 3 4]
Dernière ligne : [ 9 10 11 12]

Première colonne : [1 5 9]
Deuxième colonne : [ 2  6 10]

Sous-matrice (2x2) :
 [[1 2]
 [5 6]]


In [7]:
# Le filtrage
notes = np.array([12, 8, 15, 6, 18, 9, 14, 11, 7, 16])

# Créer un masque booléen
masque = notes >= 10
print("Masque :", masque)

# Appliquer le masque pour filtrer
admis = notes[masque]
print("Notes admis (>=10) :", admis)

# En une seule ligne
recalés = notes[notes < 10]
print("Notes recalés (<10) :", recalés)

# Combiner plusieurs conditions
mention = notes[(notes >= 14) & (notes <= 20)]
print("Mentions (14-20) :", mention)

# Compter les admis
print("\nNombre d'admis :", np.sum(notes >= 10))
print("Pourcentage d'admis :", np.mean(notes >= 10) * 100, "%")

Masque : [ True False  True False  True False  True  True False  True]
Notes admis (>=10) : [12 15 18 14 11 16]
Notes recalés (<10) : [8 6 9 7]
Mentions (14-20) : [15 18 14 16]

Nombre d'admis : 6
Pourcentage d'admis : 60.0 %


In [8]:
#Opérations vectorisées et algèbre linéaire !
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Opérations élément par élément
print("Addition :", a + b)
print("Soustraction :", b - a)
print("Multiplication :", a * b)
print("Division :", b / a)
print("Puissance :", a ** 2)

# Opérations avec un scalaire
print("\nMultiplier par 3 :", a * 3)
print("Ajouter 100 :", a + 100)

# Fonctions mathématiques
print("\nRacine carrée :", np.sqrt(b))
print("Exponentielle :", np.exp(a))
print("Logarithme :", np.log(b))

Addition : [11 22 33 44 55]
Soustraction : [ 9 18 27 36 45]
Multiplication : [ 10  40  90 160 250]
Division : [10. 10. 10. 10. 10.]
Puissance : [ 1  4  9 16 25]

Multiplier par 3 : [ 3  6  9 12 15]
Ajouter 100 : [101 102 103 104 105]

Racine carrée : [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponentielle : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithme : [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [9]:
#Algèbre linéaire (tes maths vont briller ici !) :
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Multiplication matricielle
print("Produit matricielle A x B :\n", np.dot(A, B))
# ou plus moderne :
print("\nProduit matricielle A @ B :\n", A @ B)

# Transposée
print("\nTransposée de A :\n", A.T)

# Déterminant
print("\nDéterminant de A :", np.linalg.det(A))

# Inverse
print("\nInverse de A :\n", np.linalg.inv(A))

# Vérification : A x A_inverse = Identité
print("\nA x A_inverse :\n", np.round(A @ np.linalg.inv(A)))

# Valeurs propres et vecteurs propres
valeurs, vecteurs = np.linalg.eig(A)
print("\nValeurs propres :", valeurs)
print("Vecteurs propres :\n", vecteurs)

Produit matricielle A x B :
 [[19 22]
 [43 50]]

Produit matricielle A @ B :
 [[19 22]
 [43 50]]

Transposée de A :
 [[1 3]
 [2 4]]

Déterminant de A : -2.0000000000000004

Inverse de A :
 [[-2.   1. ]
 [ 1.5 -0.5]]

A x A_inverse :
 [[1. 0.]
 [0. 1.]]

Valeurs propres : [-0.37228132  5.37228132]
Vecteurs propres :
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [11]:
#Statistiques avec NumPy
data = np.array([23, 45, 12, 67, 34, 89, 23, 45, 56, 78, 34, 56])

# Statistiques de base
print("Moyenne :", np.mean(data))
print("Médiane :", np.median(data))
print("Écart-type :", np.std(data))
print("Variance :", np.var(data))

# Min, Max, Somme
print("\nMin :", np.min(data))
print("Max :", np.max(data))
print("Somme :", np.sum(data))

# Percentiles (très utilisés en data science !)
print("\n25ème percentile :", np.percentile(data, 25))
print("50ème percentile :", np.percentile(data, 50))
print("75ème percentile :", np.percentile(data, 75))

# Trier
print("\nDonnées triées :", np.sort(data))
print("Tri décroissant :", np.sort(data)[::-1])
print("Indices triés :", np.argsort(data))

Moyenne : 46.833333333333336
Médiane : 45.0
Écart-type : 22.37868529551179
Variance : 500.8055555555556

Min : 12
Max : 89
Somme : 562

25ème percentile : 31.25
50ème percentile : 45.0
75ème percentile : 58.75

Données triées : [12 23 23 34 34 45 45 56 56 67 78 89]
Tri décroissant : [89 78 67 56 56 45 45 34 34 23 23 12]
Indices triés : [ 2  0  6  4 10  1  7  8 11  3  9  5]


In [ ]:
**Exercice pratique !**
Contexte : Tu es data scientist dans une startup qui analyse les performances de ses commerciaux.
Voici les données :
python# Ventes réalisées par 5 commerciaux sur 4 trimestres (en milliers de FCFA)
ventes = np.array([[120, 150, 130, 160],
                   [90,  110, 95,  120],
                   [200, 180, 210, 220],
                   [75,  80,  70,  90],
                   [160, 170, 155, 180]])

commerciaux = ["Alice", "Bob", "Carol", "David", "Eve"]
trimestres  = ["T1", "T2", "T3", "T4"]
Ton travail :

Affiche la forme de la matrice et le nombre total d'éléments
Calcule le total des ventes par commercial (somme sur les 4 trimestres)
Calcule la moyenne des ventes par trimestre (moyenne sur les 5 commerciaux)
Trouve le meilleur commercial (celui qui a le plus vendu au total)
Filtre les commerciaux qui ont fait plus de 500k FCFA au total
Calcule la matrice de corrélation entre les trimestres


💡 Indice pour le point 6 : utilise np.corrcoef(ventes.T)

In [40]:
#Affiche la forme de la matrice et le nombre total d'éléments
ventes = np.array([[120, 150, 130, 160],
                   [90,  110, 95,  120],
                   [200, 180, 210, 220],
                   [75,  80,  70,  90],
                   [160, 170, 155, 180]])
forme=ventes.shape
nombre_total_elements=ventes.size
print(f"la forme de la matrice est de: {forme} et le nombre total d'élements est de: {nombre_total_elements}")

#Calcule le total des ventes par commercial (somme sur les 4 trimestres)
commerciaux = ["Alice", "Bob", "Carol", "David", "Eve"]

for i in range(len(commerciaux)):
    print("Commercial",commerciaux[i]," a vendu:",np.sum(ventes[i,:]),"FCFA")
    
#Calcule la moyenne des ventes par trimestre (moyenne sur les 5 commerciaux)
print("\n")
trimestres  = ["T1", "T2", "T3", "T4"]
for i in range(len(trimestres)):
    print("Au trimestre",trimestres[i]," on a vendu en moyenne:",np.mean(ventes[:,i]),"FCFA")

#Trouve le meilleur commercial (celui qui a le plus vendu au total)
montant_max=0
meilleur_commercial=""
for i in range(len(commerciaux)):
      ventes_actuelles=np.sum(ventes[i,:])
      if ventes_actuelles > montant_max:
        montant_max=ventes_actuelles
        meilleur_commercial= commerciaux[i]
print("Le meilleur commercial est", meilleur_commercial, "avec", montant_max, "FCFA")
print("\n")
#Filtre les commerciaux qui ont fait plus de 500k FCFA au total
for i in range(len(commerciaux)):
      ventes_actuelles=np.sum(ventes[i,:])
      if ventes_actuelles > 500:
       print("Le commercial ",commerciaux[i]," a fait plus de 500k FCFA")

#Calcule la matrice de corrélation entre les trimestres
print("\n")
print(np.corrcoef(ventes.T))

la forme de la matrice est de: (5, 4) et le nombre total d'élements est de: 20
Commercial Alice  a vendu: 560 FCFA
Commercial Bob  a vendu: 415 FCFA
Commercial Carol  a vendu: 810 FCFA
Commercial David  a vendu: 315 FCFA
Commercial Eve  a vendu: 665 FCFA


Au trimestre T1  on a vendu en moyenne: 129.0 FCFA
Au trimestre T2  on a vendu en moyenne: 138.0 FCFA
Au trimestre T3  on a vendu en moyenne: 132.0 FCFA
Au trimestre T4  on a vendu en moyenne: 154.0 FCFA
Le meilleur commercial est Carol avec 810 FCFA


Le commercial  Alice  a fait plus de 500k FCFA
Le commercial  Carol  a fait plus de 500k FCFA
Le commercial  Eve  a fait plus de 500k FCFA


[[1.         0.937398   0.99141363 0.98085131]
 [0.937398   1.         0.94188583 0.97568488]
 [0.99141363 0.94188583 1.         0.99192385]
 [0.98085131 0.97568488 0.99192385 1.        ]]


In [41]:
totaux = np.sum(ventes, axis=1)
print(totaux)

[560 415 810 315 665]


In [ ]:
#corrigé

# 1. Forme et taille
print(f"Forme : {ventes.shape} | Éléments : {ventes.size}")

# 2. Total des ventes par commercial (axis=1 = sur les colonnes)
totaux = np.sum(ventes, axis=1)
for nom, total in zip(commerciaux, totaux):
    print(f"{nom} : {total}k FCFA")

# 3. Moyenne par trimestre (axis=0 = sur les lignes)
moyennes = np.mean(ventes, axis=0)
for trim, moy in zip(trimestres, moyennes):
    print(f"{trim} : {moy:.1f}k FCFA")

# 4. Meilleur commercial (sans boucle !)
index_max = np.argmax(totaux)
print(f"\nMeilleur commercial : {commerciaux[index_max]} avec {totaux[index_max]}k FCFA")

# 5. Filtre sans boucle !
masque = totaux > 500
for nom, ok in zip(commerciaux, masque):
    if ok:
        print(f"{nom} a fait plus de 500k FCFA")

# 6. Matrice de corrélation
print("\nCorrélation :\n", np.round(np.corrcoef(ventes.T), 2))

**Les différences clés :**
axis=1 et axis=0 — au lieu de boucler sur les lignes :

axis=1 → opération sur les colonnes (par commercial)
axis=0 → opération sur les lignes (par trimestre)

np.argmax() — au lieu de ta boucle pour trouver le max, NumPy retourne directement l'indice du maximum !
zip() — permet de parcourir deux listes en même temps proprement.